excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://gentokozuma.github.io
title: mainsite
author: Gento Kozuma
description: Main site for all blogs by gento
paginate: 5
google_analystics:
